// deploy
export const UPDATE_SELECTED_APP = 'UPDATE_SELECTED_APP';

// configuration

export const INIT_CONFIGURATION = 'INIT_CONFIGURATION';

export const UPDATE_LABEL = 'UPDATE_LABEL';

export const INSERT_LABEL = 'INSERT_LABEL';

export const DELETE_LABEL = 'DELETE_LABEL';

export const UPDATE_CLASSIFICATIONS = 'UPDATE_CLASSIFICATIONS';

export const INSERT_CLASSIFICATIONS = 'INSERT_CLASSIFICATIONS';

export const DELETE_CLASSIFICATIONS = 'DELETE_CLASSIFICATIONS';

// formbuilder

export const DELETE_SCHEMA = 'DELETE_SCHEMA';

export const UPDATE_SCHEMA = 'UPDATE_SCHEMA';

export const UPDATE_SCHEMA_OPTION = 'UPDATE_SCHEMA_OPTION';

export const DELETE_SCHEMA_OPTION = 'DELETE_SCHEMA_OPTION';

export const INSERT_SCHEMA_OPTION = 'INSERT_SCHEMA_OPTION';

export const INSERT_SCHEMA = 'INSERT_SCHEMA';

export const SET_ACTIVE_SCHEMA = 'SET_ACTIVE_SCHEMA';

export const EXCHANG_ESCHEMA = 'EXCHANG_ESCHEMA';

export const UPDATE_TEMPLATE_BASIC_INFO = 'UPDATE_TEMPLATE_BASIC_INFO';

export const INSERT_TEMPLATE_CLASS = 'INSERT_TEMPLATE_CLASS';

export const SET_ACTIVE_TEMPLATE_CLASSES = 'SET_ACTIVE_TEMPLATE_CLASSES';

export const SET_OPENED_TEMPLATE_CLASSES = 'SET_OPENED_TEMPLATE_CLASSES';

export const INSERT_TEMPLATE_PROPERTIES = 'INSERT_TEMPLATE_PROPERTIES';

export const REFRESH_ROLELIST = 'REFRESH_ROLELIST';

export const INSERT_ROLELIST = 'INSERT_ROLELIST';

export const UPDATE_ROLELIST = 'UPDATE_ROLELIST';

export const DELETE_ROLELIST = 'DELETE_ROLELIST';

export const REFRESH_MEMBERLIST = 'REFRESH_MEMBERLIST';

export const INSERT_MEMBERLIST = 'INSERT_MEMBERLIST';

export const UPDATE_MEMBERLIST = 'UPDATE_MEMBERLIST';

export const DELETE_MEMBERLIST = 'DELETE_MEMBERLIST';

// knowledgeDetail
export const CHANGE_ID_START = 'CHANGE_ID_START';

export const CHANGE_ID_END = 'CHANGE_ID_END';

export const GET_KNOWLEDGE_DETAIL = 'GET_KNOWLEDGE_DETAIL';

export const CHANGE_COMMENTS = 'CHANGE_COMMENTS';

export const CHANGE_IFCOLLECT = 'CHANGE_IFCOLLECT';

export const CHANGE_COLLECTS = 'CHANGE_COLLECTS';

export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';

export const CHANGE_STACK = 'CHANGE_STACK';

