<!DOCTYPE html><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core_rt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%
  String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()+ request.getContextPath() + "/";
%><c:set var="ctx" value="${pageContext.request.contextPath}"/><c:set var="isVcg" value="${sessionScope.accessKey=='pre.dam.vcg.com'}"/><html lang="zh-cmn-Hans"><head><!-- Copyright 2017 by Jintongsoft
@author Ding <ding.yuchao@jintongsoft.cn> --><base href="<%=basePath%>"><meta charset="utf-8"><meta name="referrer" content="no-referrer"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta name="renderer" content="webkit"><meta name="keyword" content="金童云平台,金童,云平台,智能机器人"><link type="text/css" rel="stylesheet" href="//localhost:9243/74.css"><link type="text/css" rel="stylesheet" href="//localhost:9243/17.css"><title>金童智能客服云平台</title></head><body class="nav-md"><nav class="navbar navbar-default"><div class="container-fluid"><div class="navbar-header"><a class="navbar-brand" href="./"><span class="primary-title">金童软件</span></a></div><div class="collapse navbar-collapse"><ul class="nav navbar-nav navbar-right"><li><a href="//www.jintongsoft.cn" target="_blank"><span class="primary-title">首页</span></a></li><li><a href="//openapi.jintongsoft.cn/qa" target="_blank"><span class="primary-title">社区</span></a></li><li><a href="//ta.jintongsoft.cn/" target="_blank"><span class="primary-title">TA情感社区</span></a></li><li><a href="//www.jintongsoft.cn/joinus.html" target="_blank"><span class="primary-title">加入我们</span></a></li><li><a href="${csclientUrl}68e84482012d42669c605187030e9e59" target="_blank"><span class="primary-title">智能客服体验</span></a></li><li><a href="./" target="_blank"><span class="primary-title">金童云平台</span></a></li></ul></div></div></nav><div class="container primary-container"><div class="login-wrapper"><div class="login-box"><div class="login-box-header"><h1>智能机器人云平台</h1></div><div class="login-box-body"><form id="login-form" method="post" action="${ctx}/logon"><div class="input-groups"><div class="input-wrapper"><input name="username" type="text" placeholder="账号"></div><div class="input-wrapper"><input name="password" type="password" placeholder="密码"></div><div class="input-wrapper code-input"><input name="yzcode" type="text" placeholder="验证码" maxlength="4"><div class="code-wrapper"><img id="code-img" src="${ctx}/ValidateCodeImage?<%=System.currentTimeMillis()%>" alt="验证码" title="点击刷新验证码"></div></div></div><c:if test="${param.errorMessage != null}"><div class="error-wrapper"><div class="error-text"><%=java.net.URLDecoder.decode(request.getParameter("errorMessage"), "UTF-8")%></div></div></c:if><div class="button-wrapper"><button type="submit">登录</button></div><div class="link-wrapper"><a class="reset-link" href="${ctx}/register/resetPwd">无法登录</a></div></form></div></div></div></div><div id="particles"></div><script>var ctx="${ctx}";
var isVcg=${isVcg};</script><script src="//localhost:9243/74.js"></script><script src="//localhost:9243/17.js"></script><!--[if lte IE 9]>
<script src='${ctx}/module/placeholders/placeholders.jquery.min.js'></script>
<![endif]--></body></html>